export type PublicPlace = {
  id: string;
  status: "published";
  country: "JP";
  nameKoOrOriginal: string;
  nameLocal?: string;
  city: string;
  area?: string;
  lat: number;
  lng: number;
  categoryTags: string[];
  commentKoAuto?: string;
  sourceVideoId: string;
  sourceVideoTitle: string;
  sourceVideoUrl: string;
  thumbnailUrl: string;
  googleMapsUrl?: string;
  placeTypeKo?: string;
  signatureKo?: string;
  whyKo?: string;
  displayDescriptionKo?: string;
  broadCategoryKo?: "밥" | "디저트" | "술";
  generatedAt: string;
};

export type DataStatus = {
  dataGenerated: boolean;
  reason?: string;
  generatedAt: string | null;
  channelHandle: string;
  videosScanned: number;
  likelyShorts: number;
  ownerCommentCandidates: number;
  japanCandidates: number;
  geocoded: number;
  published: number;
  excludedNegativeSignal: number;
  needsGeocode: number;
  heldBack: number;
  heldBackLowConfidence?: number;
  heldBackMissingGeocode?: number;
  heldBackNonJapan?: number;
};
